# Generated by Django 6.0.3 on 2026-03-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('active', 'Активный'), ('completed', 'Завершен'), ('frozen', 'Заморожен')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
